#!/bin/bash

# DNSMasq Configuration Fix Script
# This script fixes the "illegal repeated keyword" error

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m'

echo -e "${YELLOW}修复 DNSMasq 配置问题...${NC}"

# Stop dnsmasq first
systemctl stop dnsmasq 2>/dev/null

# Backup current config
if [ -f /etc/dnsmasq.conf ]; then
    cp /etc/dnsmasq.conf /etc/dnsmasq.conf.error.bak.$(date +%Y%m%d%H%M%S)
    echo -e "${YELLOW}已备份错误的配置文件${NC}"
fi

# Get server IP
SERVER_IP=$(ip -4 addr show | grep -oE 'inet [0-9.]+' | grep -v '127.0.0.1' | awk '{print $2}' | head -n1)
if [ -z "$SERVER_IP" ]; then
    SERVER_IP="127.0.0.1"
fi

echo -e "${YELLOW}使用服务器 IP: $SERVER_IP${NC}"

# Create a clean dnsmasq.conf without duplicates
cat > /etc/dnsmasq.conf << EOF
# DNSMasq Configuration
# Generated by SNIProxy Installer - Fixed Version

port=53
domain-needed
bogus-priv
no-resolv
resolv-file=/etc/resolv.dnsmasq.conf
strict-order
no-hosts
listen-address=127.0.0.1,$SERVER_IP
cache-size=10000
log-queries
log-facility=/var/log/dnsmasq.log

# China DNS servers for CN domains
server=/cn/223.5.5.5
server=/cn/119.29.29.29

# Streaming service domains - Netflix
server=/netflix.com/$SERVER_IP
server=/netflix.net/$SERVER_IP
server=/nflximg.com/$SERVER_IP
server=/nflximg.net/$SERVER_IP
server=/nflxvideo.net/$SERVER_IP
server=/nflxext.com/$SERVER_IP
server=/nflxso.net/$SERVER_IP

# Disney+
server=/disney.com/$SERVER_IP
server=/disneyplus.com/$SERVER_IP
server=/disney-plus.net/$SERVER_IP
server=/dssott.com/$SERVER_IP
server=/disneystreaming.com/$SERVER_IP

# HBO Max
server=/hbo.com/$SERVER_IP
server=/hbomax.com/$SERVER_IP
server=/max.com/$SERVER_IP
server=/hbomaxcdn.com/$SERVER_IP

# YouTube
server=/youtube.com/$SERVER_IP
server=/youtubei.googleapis.com/$SERVER_IP

# Amazon Prime Video
server=/primevideo.com/$SERVER_IP
server=/amazonvideo.com/$SERVER_IP
server=/aiv-cdn.net/$SERVER_IP
server=/aiv-delivery.net/$SERVER_IP

# AI Platforms
server=/openai.com/$SERVER_IP
server=/chatgpt.com/$SERVER_IP
server=/anthropic.com/$SERVER_IP
server=/claude.ai/$SERVER_IP

# TikTok
server=/tiktok.com/$SERVER_IP
server=/byteoversea.com/$SERVER_IP

# Popular streaming services
server=/hulu.com/$SERVER_IP
server=/crunchyroll.com/$SERVER_IP
server=/twitch.tv/$SERVER_IP
EOF

# Ensure upstream DNS config exists
if [ ! -f /etc/resolv.dnsmasq.conf ]; then
    cat > /etc/resolv.dnsmasq.conf << EOF
nameserver 8.8.8.8
nameserver 1.1.1.1
nameserver 223.5.5.5
nameserver 119.29.29.29
EOF
fi

# Create log file
touch /var/log/dnsmasq.log
chmod 644 /var/log/dnsmasq.log

# Test configuration
echo -e "${YELLOW}测试配置文件语法...${NC}"
if dnsmasq --test -C /etc/dnsmasq.conf; then
    echo -e "${GREEN}✓ 配置文件语法正确${NC}"

    # Start dnsmasq
    if systemctl start dnsmasq; then
        echo -e "${GREEN}✓ DNSMasq 启动成功${NC}"

        # Enable auto start
        systemctl enable dnsmasq

        # Show status
        echo -e "${GREEN}DNSMasq 状态:${NC}"
        systemctl status dnsmasq --no-pager -l
    else
        echo -e "${RED}✗ DNSMasq 启动失败${NC}"
        echo -e "${YELLOW}查看详细错误信息:${NC}"
        journalctl -xeu dnsmasq.service --no-pager -n 20
    fi
else
    echo -e "${RED}✗ 配置文件仍有错误${NC}"
    echo -e "${YELLOW}请检查 /etc/dnsmasq.conf 文件${NC}"
fi

echo ""
echo -e "${YELLOW}修复完成！如果仍有问题，请检查:${NC}"
echo -e "1. ${YELLOW}配置文件: /etc/dnsmasq.conf${NC}"
echo -e "2. ${YELLOW}日志文件: /var/log/dnsmasq.log${NC}"
echo -e "3. ${YELLOW}系统日志: journalctl -xeu dnsmasq.service${NC}"